services:
  - type: web
    name: rails-app
    env: ruby
    buildCommand: bundle install && yarn install && bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-database
          property: connectionString

databases:
  - name: rails-database
    plan: starter
    postgresVersion: 16